### PR TITLE
CAMEL-21093 - Workaround to fix fhir auth x test due to commons-io

### PR DESCRIPTION
**Pull request by apupier**
version clash

### CODE REVIEW

**Comment by apupier** [comment]
maybe not needed with https://github.com/apupier/camel/pull/new/21093-alignCommonsIO

**Comment by apupier** [comment]
the part which is not clear to me is why we need to add in the dependencyManagement of this example or the component although we are declaring the camel springboot bom

**Comment by davsclaus** [comment]
Did you fix this in camel-fhir in the core project, or would this kind of PR still be needed here ?

**Comment by apupier** [comment]
seems the fix on camel core project is not working (or the snpashot artifact was still not pushed?) because the tests are still failing without this PR https://github.com/apache/camel-spring-boot-examples/actions/runs/10421144874?pr=137

**Comment by davsclaus** [comment]
lets merge to get the example working

**Pull request merged**
