### PR TITLE
Camel examples for spring-boot-cli

### PR DESCRIPTION
**Pull request by vinodpahuja**

### CODE REVIEW

**Comment by vinodpahuja** [comment]
@davsclaus can you please help on this

**Comment by davsclaus** [comment]
Hi @vinodpahuja 

Sorry for the delay.

At first, do you know about this git repository: https://github.com/apache-camel ?
We would like to get in contact with the owner of this repository, because Apache Software Foundation
has a concern about the naming of the repository, that infringe their brand and trademarks [1].

- https://www.apache.org/foundation/marks/domains

**Comment by vinodpahuja** [comment]
> Hi @vinodpahuja
> 
> Sorry for the delay.
> 
> At first, do you know about this git repository: https://github.com/apache-camel ? We would like to get in contact with the owner of this repository, because Apache Software Foundation has a concern about the naming of the repository, that infringe their brand and trademarks [1].
> 
> * https://www.apache.org/foundation/marks/domains

Thanks for the information, I did not realized that. 
For now I have moved the current project to another org [camel-experiments](https://github.com/camel-experiments/camel-spring-boot-examples), will move others once I commit some WIP code in other repos.

**Comment by davsclaus** [comment]
Thanks for taking action on the ASF concern

**Comment by vinodpahuja** [comment]
> @davsclaus can you please help on this

Any other inputs !!!

**Comment by vinodpahuja** [comment]
> Can you please fix the https://github.com/apache-camel first before we can talk about merging PRs to ASF.

Moved / Renamed to https://github.com/camel-experimental

**Comment by davsclaus** [comment]
The groovy source file need ASF license header.

**Comment by vinodpahuja** [comment]
@davsclaus - I just noticed that the spring-boot-cli [example](https://github.com/apache/camel-spring-boot-examples/commit/8217b6836fea95151039bdfc4993f751350537da) has been [removed](https://github.com/apache/camel-spring-boot-examples/commit/cc7866363a2cd6abaf6a32eb180ca2ea0a183201). 
Can you please help with the rational behind it ?

**Pull request merged**
