### PR TITLE
Added OpenTelemetry example

### PR DESCRIPTION
**Pull request by stn1slv**
This example demonstrates how to deal with Open Telemetry standard with Apache Camel

### CODE REVIEW

**Comment by stn1slv** [comment]
Hi @oscerd ,
I've created this pull request to provide an example of how to deal with [Open Telemetry](https://opentelemetry.io) with Apache Camel (see [OpenTelemetry component](https://camel.apache.org/components/3.20.x/others/opentelemetry.html)).

I would appreciate it if you could take some time to review my changes and provide any feedback or suggestions. Thank you in advance!

Best regards,
@stn1slv

**Review by oscerd — CHANGES_REQUESTED** [review]
Looks good overall, but you need to add the license to all the files. Thanks

**Review by oscerd — APPROVED** [review]

**Comment by stn1slv** [comment]
@davsclaus, 
I would appreciate it if you could review (as a maintainer of the repo) the changes I've proposed. 
Thanks in advance for your time and feedback.

**Comment by oscerd** [comment]
Let's wait for the build and we'll merge.

**Comment by oscerd** [comment]
Thanks @stn1slv !

**Pull request merged**
