### PR TITLE
azure camel spring boot samples for azure:

### PR DESCRIPTION
**Pull request by jialigit**
azure camel spring boot samples for azure:

1. eventhubs
2. servicebus
3. servicebus jms

### CODE REVIEW

**Comment by hui1110** [comment]
Hi @oscerd, will this PR be merged, and if so I will create a new PR to replace this one.

**Review by oscerd — CHANGES_REQUESTED** [review]
The licenses are missing everywhere.

**Comment by oscerd** [comment]
> Hi @oscerd, will these changes be merged, and if so I will create a new PR to replace this one.

It needs to be updated with licenses and aligned to 3.19.0-SNAPSHOT, so as-is we won't merge it.

**Comment by hui1110** [comment]
Hi @oscerd， I create a new PR to replace this PR. https://github.com/apache/camel-spring-boot-examples/pull/87

**Comment by davsclaus** [comment]
closing old and out-dated PRs

**Pull request closed without merging**
