### PR TITLE
 add external links for sapjcoclient and sapjocserver example

### PR DESCRIPTION
**Pull request by wangyan100**
move  examples of sapjcoclient and sapjocserver to external repo
add external links pointing to them at readme

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
The examples are still in the git tree.

**Review by oscerd — CHANGES_REQUESTED** [review]
Also the readme list is autogenerated so it will be overriden.

**Review by oscerd — CHANGES_REQUESTED** [review]
So probably we need to add list statically in another point of the README only for external examples.

**Comment by davsclaus** [comment]
The examples are only for ASF examples.

Links to other sites etc are all from our articles page at
https://camel.apache.org/community/articles/

You can send a PR to add a link there

**Pull request closed without merging**
