### PR TITLE
SAP JCOClient 

### PR DESCRIPTION
**Pull request by wangyan100**
An example showing how to work with Camel,SAP JCOClient and Spring Boot

### CODE REVIEW

**Comment by zhfeng** [comment]
Well, I think there is the other one for SAP JCO Server https://github.com/apache/camel-spring-boot-examples/pull/67 ?

**Comment by oscerd** [comment]
Removed now.

**Comment by zhfeng** [comment]
IMO, it looks more like a SAP example but not camel.

**Comment by oscerd** [comment]
It has been removed, for license problem. We could eventually add a link to examples for external sources.

**Pull request closed without merging**
